var species_list = [
[1,"Caranx fulvoguttatus ()"],
[2,"Carcharhinus amblyrhynchos ()"],
[3,"Carcharhinus cautus ()"],
[4,"Carcharhinus melanopterus ()"],
[5,"Coris aygula (Clown coris)"],
[6,"Epinephelus rivulatus (Halfmoon grouper)"],
[7,"Galocerdo cuvier (Tiger shark)"],
[8,"Lethrinus nebulosus (Spangled emperor)"],
[9,"Manta birostris (Manta ray)"],
[10,"Negaprion acutidens (Sicklefin lemon shark)"],
[11,"Pastinachus sephen (Cowtail stingray)"],
[12,"Rhinobatos typus (Giant shovelnose ray)"],
[13,"Thunnus maccoyii (Southern bluefin tuna)"],
[14,"Urogymnus asperrimus (Porcupine ray)"],
[32,"Scarus gobban (Blue-barred parrotfish)"],
[33,"Variola louti (Yellow-edged lyretail)"],
[34,"Scarus rivulatus (Rivulated parrotfish)"],
[35,"Orectolobus halei (Hale's wobbegong)"],
[36,"Chlorurus sordidus (Bullethead parrotfish)"],
[37,"Epinephelus tauvina (Greasy grouper)"],
[38,"Hiposcarus longiceps (Pacific longnose parrotfish)"],
[39,"Orectolobus maculatus (Spotted wobbegong)"],
[40,"Plectropomus leopardus (Leopard coralgrouper)"],
[41,"Plectropomus maculatus (Spotted coralgrouper)"],
[42,"Epinephelus multinotatus (White-blotched grouper)"]
];
