CREATE SEQUENCE AATAMS.ANIMAL_SERIAL;CREATE TABLE AATAMS.ANIMAL(ANIMAL_ID INTEGER PRIMARY KEY NOT NULL,
CLASSIFICATION_ID INTEGER NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISPLAY_LEVEL_ID INTEGER,
DISPLAY_START_DATE TIMESTAMP,
COMMENTS VARCHAR2(4000),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.CLASSIFICATION_SERIAL;CREATE TABLE AATAMS.CLASSIFICATION(CLASSIFICATION_ID INTEGER PRIMARY KEY NOT NULL,
PARENT_CLASSIFICATION_ID INTEGER,
CLASSIFICATION_LEVEL_ID INTEGER NOT NULL,
NAME VARCHAR2(50) NOT NULL,
COMMON_NAME VARCHAR2(50),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.CLASSIFICATION_LEVEL_SERIAL;CREATE TABLE AATAMS.CLASSIFICATION_LEVEL(CLASSIFICATION_LEVEL_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEPLOYMENT_DOWNLOAD_SERIAL;CREATE TABLE AATAMS.DEPLOYMENT_DOWNLOAD(DOWNLOAD_ID INTEGER PRIMARY KEY NOT NULL,
DEPLOYMENT_ID INTEGER NOT NULL,
RECOVERY_TIMESTAMP TIMESTAMP,
DOWNLOAD_TIMESTAMP TIMESTAMP NOT NULL,
TIME_CORRECTION_START TIMESTAMP,
TIME_CORRECTION_END TIMESTAMP,
TIME_CORRECTION_TYPE_ID VARCHAR2(50),
CLOCK_DRIFT INTEGER,
PINGS INTEGER,
DETECTIONS INTEGER,
CC_EMAIL_ADDRESSES VARCHAR2(500),
COMMENTS VARCHAR2(4000),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DOWNLOAD_TAG_SUMMARY_SERIAL;CREATE TABLE AATAMS.DOWNLOAD_TAG_SUMMARY(DOWNLOAD_ID INTEGER PRIMARY KEY NOT NULL,
DEVICE_ID INTEGER NOT NULL,
DETECTION_COUNT INTEGER NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEPLOYMENT_EVENT_SERIAL;CREATE TABLE AATAMS.DEPLOYMENT_EVENT(DEPLOYMENT_EVENT_ID INTEGER PRIMARY KEY NOT NULL,
DEPLOYMENT_ID INTEGER NOT NULL,
EVENT_TYPE_ID INTEGER NOT NULL,
EVENT_TIMESTAMP VARCHAR2(50) NOT NULL,
COMMENTS VARCHAR2(4000),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEPLOYMENT_EVENT_TYPE_SERIAL;CREATE TABLE AATAMS.DEPLOYMENT_EVENT_TYPE(EVENT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEPLOYMENT_RECOVERY_SERIAL;CREATE TABLE AATAMS.DEPLOYMENT_RECOVERY(RECOVERY_ID INTEGER PRIMARY KEY NOT NULL,
DEPLOYMENT_ID INTEGER NOT NULL,
RECOVERY_TIMESTAMP TIMESTAMP NOT NULL,
RECOVERY_STATUS_ID INTEGER,
COMMENTS VARCHAR2(4000),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.RECOVERY_STATUS_SERIAL;CREATE TABLE AATAMS.RECOVERY_STATUS(RECOVERY_STATUS_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DETECTION_SERIAL;CREATE TABLE AATAMS.DETECTION(DETECTION_ID INTEGER PRIMARY KEY NOT NULL,
DEPLOYMENT_ID INTEGER NOT NULL,
DOWNLOAD_ID INTEGER,
TAG_ID INTEGER NOT NULL,
DETECTION_TIMESTAMP TIMESTAMP NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEVICE_SERIAL;CREATE TABLE AATAMS.DEVICE(DEVICE_ID INTEGER PRIMARY KEY NOT NULL,
CODE_NAME VARCHAR2(50) NOT NULL,
DEVICE_TYPE_ID INTEGER NOT NULL,
MODEL_ID INTEGER NOT NULL,
SERIAL_NUMBER VARCHAR2(50) NOT NULL,
PROJECT_ROLE_PERSON_ID INTEGER NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEVICE_DEPLOYER_SERIAL;CREATE TABLE AATAMS.DEVICE_DEPLOYER(DEVICE_DEPLOYER_ID INTEGER PRIMARY KEY NOT NULL,
DEPLOYMENT_ID INTEGER NOT NULL,
PERSON_ID INTEGER NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.RECEIVER_DEPLOYMENT_SERIAL;CREATE TABLE AATAMS.RECEIVER_DEPLOYMENT(DEPLOYMENT_ID INTEGER PRIMARY KEY NOT NULL,
DEVICE_ID INTEGER NOT NULL,
INSTALLATION_ID INTEGER NOT NULL,
STATION_ID INTEGER,
PROJECT_ROLE_PERSON_ID INTEGER NOT NULL,
LONGITUDE NUMBER(8,5) NOT NULL,
LATITUDE NUMBER(7,5) NOT NULL,
DEPLOYMENT_TIMESTAMP TIMESTAMP NOT NULL,
ACOUSTIC_RELEASE_ID VARCHAR2(50),
MOORING_TYPE_ID INTEGER,
BOTTOM_DEPTH NUMBER(5,2) NOT NULL,
COMMENTS VARCHAR2(4000),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEVICE_MANUFACTURER_SERIAL;CREATE TABLE AATAMS.DEVICE_MANUFACTURER(MANUFACTURER_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEVICE_MODEL_SERIAL;CREATE TABLE AATAMS.DEVICE_MODEL(MODEL_ID INTEGER PRIMARY KEY NOT NULL,
DEVICE_TYPE_ID INTEGER NOT NULL,
MANUFACTURER_ID INTEGER NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DEVICE_TYPE_SERIAL;CREATE TABLE AATAMS.DEVICE_TYPE(DEVICE_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.DOWNLOAD_FILE_SERIAL;CREATE TABLE AATAMS.DOWNLOAD_FILE(DOWNLOAD_FILE_ID INTEGER PRIMARY KEY NOT NULL,
DOWNLOAD_ID INTEGER NOT NULL,
FILE_REFERENCE VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.GEOGRAPHIC_AREA_SERIAL;CREATE TABLE AATAMS.GEOGRAPHIC_AREA(GEOGRAPHIC_AREA_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
BOUNDARY_POINTS VARCHAR2(500),
DESCRIPTION VARCHAR2(500) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.IMPLANT_TYPE_SERIAL;CREATE TABLE AATAMS.IMPLANT_TYPE(IMPLANT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.INSTALLATION_SERIAL;CREATE TABLE AATAMS.INSTALLATION(INSTALLATION_ID INTEGER PRIMARY KEY NOT NULL,
CONFIGURATION_TYPE_ID INTEGER NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.INSTALLATION_CONF_SERIAL;CREATE TABLE AATAMS.INSTALLATION_CONF(CONFIGURATION_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.INSTALLATION_STATION_SERIAL;CREATE TABLE AATAMS.INSTALLATION_STATION(STATION_ID INTEGER PRIMARY KEY NOT NULL,
INSTALLATION_ID INTEGER NOT NULL,
CURTAIN_POSITION INTEGER,
NAME VARCHAR2(50) NOT NULL,
LONGITUDE NUMBER(8,5) NOT NULL,
LATITUDE NUMBER(7,5) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.MEASUREMENT_SERIAL;CREATE TABLE AATAMS.MEASUREMENT(MEASUREMENT_ID INTEGER PRIMARY KEY NOT NULL,
SURGERY_ID INTEGER NOT NULL,
MEASUREMENT_TYPE_ID INTEGER NOT NULL,
VALUE VARCHAR2(50) NOT NULL,
COMMENTS VARCHAR2(4000),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.MEASUREMENT_TYPE_SERIAL;CREATE TABLE AATAMS.MEASUREMENT_TYPE(MEASUREMENT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
MEASUREMENT_UNITS_ID INTEGER NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.MEASUREMENT_UNIT_TYPE_SERIAL;CREATE TABLE AATAMS.MEASUREMENT_UNIT_TYPE(MEASUREMENT_UNIT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.MOORING_TYPE_SERIAL;CREATE TABLE AATAMS.MOORING_TYPE(MOORING_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DESCRIPTION VARCHAR2(500),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.ORGANISATION_SERIAL;CREATE TABLE AATAMS.ORGANISATION(ORGANISATION_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
PHYSICAL_ADDRESS_1 VARCHAR2(100),
PHYSICAL_ADDRESS_2 VARCHAR2(100),
PHYSICAL_ADDRESS_STATE VARCHAR2(20),
PHYSICAL_ADDRESS_COUNTRY VARCHAR2(30),
PHYSICAL_ADDRESS_POSTCODE VARCHAR2(6),
POSTAL_ADDRESS_1 VARCHAR2(100),
POSTAL_ADDRESS_2 VARCHAR2(100),
POSTAL_ADDRESS_STATE VARCHAR2(20),
POSTAL_ADDRESS_COUNTRY VARCHAR2(50),
POSTAL_ADDRESS_POSTCODE VARCHAR2(6),
PHONE_NUMBER VARCHAR2(20),
FAX_NUMBER VARCHAR2(20),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.ORGANISATION_ANIMAL_SERIAL;CREATE TABLE AATAMS.ORGANISATION_ANIMAL(ORGANISATION_ANIMAL_ID VARCHAR2(50) PRIMARY KEY,
ORGANISATION_ID INTEGER NOT NULL,
ANIMAL_ID INTEGER NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.ORGANISATION_PERSON_SERIAL;CREATE TABLE AATAMS.ORGANISATION_PERSON(ORGANISATION_PERSON_ID INTEGER PRIMARY KEY NOT NULL,
PERSON_ID INTEGER NOT NULL,
ORGANISATION_ID INTEGER NOT NULL,
POSITION VARCHAR2(50) NOT NULL,
PHONE_NUMBER VARCHAR2(15),
FAX_NUMBER VARCHAR2(15),
MOBILE_NUMBER VARCHAR2(15),
EMAIL_ADDRESS VARCHAR2(50),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.PERSON_SERIAL;CREATE TABLE AATAMS.PERSON(PERSON_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
PERSONAL_MOBILE_NUMBER VARCHAR2(15),
HOME_PHONE_NUMBER VARCHAR2(15),
EMAIL VARCHAR2(30),
HOME_PHYSICAL_ADDRESS_1 VARCHAR2(50),
HOME_PHYSICAL_ADDRESS_2 VARCHAR2(50),
HOME_PHYSICAL_ADDRESS_STATE VARCHAR2(50),
HOME_PHYSICAL_ADDRESS_COUNTRY VARCHAR2(50),
HOME_PHYSICAL_ADDRESS_POSTCODE VARCHAR2(50),
HOME_POSTAL_ADDRESS_1 VARCHAR2(50),
HOME_POSTAL_ADDRESS_2 VARCHAR2(50),
HOME_POSTAL_ADDRESS_STATE VARCHAR2(50),
HOME_POSTAL_ADDRESS_COUNTRY VARCHAR2(50),
HOME_POSTAL_ADDRESS_POSTCODE VARCHAR2(50),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.PROJECT_SERIAL;CREATE TABLE AATAMS.PROJECT(PROJECT_ID INTEGER PRIMARY KEY NOT NULL,
ORGANISATION_ID INTEGER NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.PROJECT_ROLE_PERSON_SERIAL;CREATE TABLE AATAMS.PROJECT_ROLE_PERSON(PROJECT_ROLE_PERSON_ID INTEGER PRIMARY KEY NOT NULL,
PROJECT_ID INTEGER NOT NULL,
ROLE_ID INTEGER NOT NULL,
PERSON_ID INTEGER NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.ROLE_SERIAL;CREATE TABLE AATAMS.ROLE(ROLE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.STATUS_SERIAL;CREATE TABLE AATAMS.STATUS(STATUS_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.STOCK_SERIAL;CREATE TABLE AATAMS.STOCK(STOCK_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.SURGERY_SERIAL;CREATE TABLE AATAMS.SURGERY(SURGERY_ID INTEGER PRIMARY KEY NOT NULL,
TREATMENT_TYPE_ID INTEGER NOT NULL,
PROJECT_ROLE_PERSON_ID INTEGER NOT NULL,
ANIMAL_ID INTEGER NOT NULL,
STOCK_ID INTEGER,
UTC_DATETIME TIMESTAMP NOT NULL,
COMMENTS VARCHAR2(4000),
UNIT VARCHAR2(50) NOT NULL,
MEASURE VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.SURGERY_PERSON_SERIAL;CREATE TABLE AATAMS.SURGERY_PERSON(SURGERY_PERSON_ID INTEGER PRIMARY KEY NOT NULL,
SURGERY_ID INTEGER NOT NULL,
PERSON_ID INTEGER NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.TAG_DEVICE_SERIAL;CREATE TABLE AATAMS.TAG_DEVICE(DEVICE_ID INTEGER PRIMARY KEY NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.TAG_FAMILY_SERIAL;CREATE TABLE AATAMS.TAG_FAMILY(TAG_FAMILY_ID INTEGER PRIMARY KEY NOT NULL,
MANUFACTURER_ID INTEGER NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.TAG_MODEL_SERIAL;CREATE TABLE AATAMS.TAG_MODEL(MODEL_ID INTEGER PRIMARY KEY NOT NULL,
TAG_FAMILY_ID INTEGER NOT NULL,
VUE_CODING VARCHAR2(50) NOT NULL,
TAG_TYPE_ID INTEGER NOT NULL,
FREQUENCY VARCHAR2(50) NOT NULL,
SYNC VARCHAR2(50) NOT NULL,
BIN VARCHAR2(50) NOT NULL,
MIN INTEGER NOT NULL,
MAX INTEGER NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.TAG_RELEASE_SERIAL;CREATE TABLE AATAMS.TAG_RELEASE(RELEASE_ID INTEGER PRIMARY KEY NOT NULL,
DEVICE_ID INTEGER NOT NULL,
CLASSIFICATION_ID INTEGER NOT NULL,
PROJECT_ROLE_PERSON_ID INTEGER NOT NULL,
RELEASE_LONGITUDE NUMBER(8,5) NOT NULL,
RELEASE_LATITUDE NUMBER(7,5) NOT NULL,
RELEASE_TIMESTAMP TIMESTAMP NOT NULL,
CAPTURE_LONGITUDE NUMBER(8,5),
CAPTURE_LATITUDE NUMBER(7,5),
CAPTURE_TIMESTAMP TIMESTAMP,
IMPLANT_TYPE_ID INTEGER,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.TAG_TYPE_SERIAL;CREATE TABLE AATAMS.TAG_TYPE(TAG_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
MANUFACTURER_ID INTEGER NOT NULL,
NAME VARCHAR2(10) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.TETHER_TYPE_SERIAL;CREATE TABLE AATAMS.TETHER_TYPE(TETHER_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DESCRIPTION VARCHAR2(50) NOT NULL,
PICTURE_REFERENCE VARCHAR2(4000),
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);CREATE SEQUENCE AATAMS.TREATMENT_TYPE_SERIAL;CREATE TABLE AATAMS.TREATMENT_TYPE(TREATMENT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL);ALTER TABLE AATAMS.ANIMALADD CONSTRAINT ANIMAL_FK00FOREIGN KEY(CLASSIFICATION_ID)REFERENCES AATAMS.CLASSIFICATION(CLASSIFICATION_ID);ALTER TABLE AATAMS.CLASSIFICATIONADD CONSTRAINT CLASSIFICATION_FK00FOREIGN KEY(CLASSIFICATION_LEVEL_ID)REFERENCES AATAMS.CLASSIFICATION_LEVEL(CLASSIFICATION_LEVEL_ID);ALTER TABLE AATAMS.CLASSIFICATIONADD CONSTRAINT CLASSIFICATION_FK01FOREIGN KEY(PARENT_CLASSIFICATION_ID)REFERENCES AATAMS.CLASSIFICATION(CLASSIFICATION_ID);ALTER TABLE AATAMS.DEPLOYMENT_DOWNLOADADD CONSTRAINT DEPLOYMENT_DOWNLOAD_FK00FOREIGN KEY(DEPLOYMENT_ID)REFERENCES AATAMS.INSTALLATION_DEPLOYMENT(DEPLOYMENT_ID);ALTER TABLE AATAMS.DOWNLOAD_TAG_SUMMARYADD CONSTRAINT DOWNLOAD_TAG_SUMMARY_FK00FOREIGN KEY(DOWNLOAD_ID)REFERENCES AATAMS.DEPLOYMENT_DOWNLOAD(DOWNLOAD_ID);ALTER TABLE AATAMS.DOWNLOAD_TAG_SUMMARYADD CONSTRAINT DOWNLOAD_TAG_SUMMARY_FK01FOREIGN KEY(DEVICE_ID)REFERENCES AATAMS.DEVICE(DEVICE_ID);ALTER TABLE AATAMS.DEPLOYMENT_EVENTADD CONSTRAINT DEPLOYMENT_EVENT_FK00FOREIGN KEY(EVENT_TYPE_ID)REFERENCES AATAMS.DEPLOYMENT_EVENT_TYPE(EVENT_TYPE_ID);ALTER TABLE AATAMS.DEPLOYMENT_EVENTADD CONSTRAINT DEPLOYMENT_EVENT_FK01FOREIGN KEY(DEPLOYMENT_ID)REFERENCES AATAMS.INSTALLATION_DEPLOYMENT(DEPLOYMENT_ID);ALTER TABLE AATAMS.DEPLOYMENT_RECOVERYADD CONSTRAINT DEPLOYMENT_RECOVERY_FK00FOREIGN KEY(DEPLOYMENT_ID)REFERENCES AATAMS.INSTALLATION_DEPLOYMENT(DEPLOYMENT_ID);ALTER TABLE AATAMS.DEPLOYMENT_RECOVERYADD CONSTRAINT DEPLOYMENT_RECOVERY_FK01FOREIGN KEY(RECOVERY_STATUS_ID)REFERENCES AATAMS.RECOVERY_STATUS(RECOVERY_STATUS_ID);ALTER TABLE AATAMS.DETECTIONADD CONSTRAINT DETECTION_FK00FOREIGN KEY(DEPLOYMENT_ID)REFERENCES AATAMS.INSTALLATION_DEPLOYMENT(DEPLOYMENT_ID);ALTER TABLE AATAMS.DEVICEADD CONSTRAINT DEVICE_FK00FOREIGN KEY(MODEL_ID)REFERENCES AATAMS.DEVICE_MODEL(MODEL_ID);ALTER TABLE AATAMS.DEVICEADD CONSTRAINT DEVICE_FK01FOREIGN KEY(DEVICE_TYPE_ID)REFERENCES AATAMS.DEVICE_TYPE(DEVICE_TYPE_ID);ALTER TABLE AATAMS.DEVICEADD CONSTRAINT DEVICE_FK02FOREIGN KEY(PROJECT_ROLE_PERSON_ID)REFERENCES AATAMS.PROJECT_PERSON(PROJECT_ROLE_PERSON_ID);ALTER TABLE AATAMS.RECEIVER_DEPLOYMENTADD CONSTRAINT RECEIVER_DEPLOYMENT_FK00FOREIGN KEY(DEVICE_ID)REFERENCES AATAMS.RECEIVER_DEVICE(DEVICE_ID);ALTER TABLE AATAMS.RECEIVER_DEPLOYMENTADD CONSTRAINT RECEIVER_DEPLOYMENT_FK02FOREIGN KEY(INSTALLATION_ID)REFERENCES AATAMS.INSTALLATION(INSTALLATION_ID);ALTER TABLE AATAMS.RECEIVER_DEPLOYMENTADD CONSTRAINT RECEIVER_DEPLOYMENT_FK01FOREIGN KEY(STATION_ID)REFERENCES AATAMS.STATION(STATION_ID);ALTER TABLE AATAMS.RECEIVER_DEPLOYMENTADD CONSTRAINT RECEIVER_DEPLOYMENT_FK03FOREIGN KEY(MOORING_TYPE_ID)REFERENCES AATAMS.MOORING_TYPE(MOORING_TYPE_ID);ALTER TABLE AATAMS.RECEIVER_DEPLOYMENTADD CONSTRAINT RECEIVER_DEPLOYMENT_FK04FOREIGN KEY(PROJECT_ROLE_PERSON_ID)REFERENCES AATAMS.PROJECT_PERSON(PROJECT_ROLE_PERSON_ID);ALTER TABLE AATAMS.DEVICE_MODELADD CONSTRAINT DEVICE_MODEL_FK00FOREIGN KEY(MANUFACTURER_ID)REFERENCES AATAMS.DEVICE_MANUFACTURER(MANUFACTURER_ID);ALTER TABLE AATAMS.DEVICE_MODELADD CONSTRAINT DEVICE_MODEL_FK01FOREIGN KEY(DEVICE_TYPE_ID)REFERENCES AATAMS.DEVICE_TYPE(DEVICE_TYPE_ID);ALTER TABLE AATAMS.DOWNLOAD_FILEADD CONSTRAINT DOWNLOAD_FILE_FK00FOREIGN KEY(DOWNLOAD_ID)REFERENCES AATAMS.DEPLOYMENT_DOWNLOAD(DOWNLOAD_ID);ALTER TABLE AATAMS.INSTALLATIONADD CONSTRAINT INSTALLATION_FK00FOREIGN KEY(GEOGRAPHIC_AREA_ID)REFERENCES AATAMS.GEOGRAPHIC_AREA(GEOGRAPHIC_AREA_ID);ALTER TABLE AATAMS.INSTALLATIONADD CONSTRAINT INSTALLATION_FK01FOREIGN KEY(CONFIGURATION_TYPE_ID)REFERENCES AATAMS.INSTALLATION_CONF(CONFIGURATION_TYPE_ID);ALTER TABLE AATAMS.INSTALLATION_STATIONADD CONSTRAINT INSTALLATION_STATION_FK00FOREIGN KEY(INSTALLATION_ID)REFERENCES AATAMS.INSTALLATION(INSTALLATION_ID);ALTER TABLE AATAMS.MEASUREMENTADD CONSTRAINT MEASUREMENT_FK00FOREIGN KEY(MEASUREMENT_TYPE_ID)REFERENCES AATAMS.MEASUREMENT_TYPE(MEASUREMENT_TYPE_ID);ALTER TABLE AATAMS.MEASUREMENTADD CONSTRAINT MEASUREMENT_FK01FOREIGN KEY(SURGERY_ID)REFERENCES AATAMS.SURGERY(SURGERY_ID);ALTER TABLE AATAMS.MEASUREMENT_TYPEADD CONSTRAINT MEASUREMENT_TYPE_FK00FOREIGN KEY(MEASUREMENT_UNITS_ID)REFERENCES AATAMS.MEASUREMENT_UNIT_TYPE(MEASUREMENT_UNIT_TYPE_ID);ALTER TABLE AATAMS.PROJECTADD CONSTRAINT PROJECT_FK00FOREIGN KEY(ORGANISATION_ID)REFERENCES AATAMS.ORGANISATION(ORGANISATION_ID);ALTER TABLE AATAMS.PROJECT_ROLE_PERSONADD CONSTRAINT PROJECT_ROLE_PERSON_FK00FOREIGN KEY(PERSON_ID)REFERENCES AATAMS.PERSON(PERSON_ID);ALTER TABLE AATAMS.PROJECT_ROLE_PERSONADD CONSTRAINT PROJECT_ROLE_PERSON_FK01FOREIGN KEY(PROJECT_ID)REFERENCES AATAMS.PROJECT(PROJECT_ID);ALTER TABLE AATAMS.PROJECT_ROLE_PERSONADD CONSTRAINT PROJECT_ROLE_PERSON_FK02FOREIGN KEY(ROLE_ID)REFERENCES AATAMS.ROLE(ROLE_ID);ALTER TABLE AATAMS.SURGERYADD CONSTRAINT SURGERY_FK00FOREIGN KEY(ANIMAL_ID)REFERENCES AATAMS.ANIMAL(ANIMAL_ID);ALTER TABLE AATAMS.SURGERYADD CONSTRAINT SURGERY_FK01FOREIGN KEY(TREATMENT_TYPE_ID)REFERENCES AATAMS.TREATMENT_TYPE(TREATMENT_TYPE_ID);ALTER TABLE AATAMS.SURGERYADD CONSTRAINT SURGERY_FK02FOREIGN KEY(PROJECT_ROLE_PERSON_ID)REFERENCES AATAMS.PROJECT_PERSON(PROJECT_ROLE_PERSON_ID);ALTER TABLE AATAMS.SURGERY_PERSONADD CONSTRAINT SURGERY_PERSON_FK00FOREIGN KEY(PERSON_ID)REFERENCES AATAMS.PERSON(PERSON_ID);ALTER TABLE AATAMS.SURGERY_PERSONADD CONSTRAINT SURGERY_PERSON_FK01FOREIGN KEY(SURGERY_ID)REFERENCES AATAMS.SURGERY(SURGERY_ID);ALTER TABLE AATAMS.TAG_MODELADD CONSTRAINT TAG_MODEL_FK00FOREIGN KEY(MODEL_ID)REFERENCES AATAMS.DEVICE_MODEL(MODEL_ID);ALTER TABLE AATAMS.TAG_MODELADD CONSTRAINT TAG_MODEL_FK01FOREIGN KEY(TAG_FAMILY_ID)REFERENCES AATAMS.TAG_FAMILY(TAG_FAMILY_ID);ALTER TABLE AATAMS.TAG_MODELADD CONSTRAINT TAG_MODEL_FK02FOREIGN KEY(TAG_TYPE_ID)REFERENCES AATAMS.TAG_TYPE(TAG_TYPE_ID);ALTER TABLE AATAMS.TAG_RELEASEADD CONSTRAINT TAG_RELEASE_FK00FOREIGN KEY(CLASSIFICATION_ID)REFERENCES AATAMS.CLASSIFICATION(CLASSIFICATION_ID);ALTER TABLE AATAMS.TAG_RELEASEADD CONSTRAINT TAG_RELEASE_FK01FOREIGN KEY(DEVICE_ID)REFERENCES AATAMS.TRANSMITTER_DEVICE(DEVICE_ID);ALTER TABLE AATAMS.TAG_RELEASEADD CONSTRAINT TAG_RELEASE_FK02FOREIGN KEY(IMPLANT_TYPE_ID)REFERENCES AATAMS.IMPLANT_TYPE(IMPLANT_TYPE_ID);ALTER TABLE AATAMS.TAG_RELEASEADD CONSTRAINT TAG_RELEASE_FK04FOREIGN KEY(PROJECT_ROLE_PERSON_ID)REFERENCES AATAMS.PROJECT_PERSON(PROJECT_ROLE_PERSON_ID);