
CREATE SEQUENCE AATAMS_2.ANIMAL_SERIAL;
CREATE TABLE AATAMS_2.ANIMAL
(
   ANIMAL_ID INTEGER PRIMARY KEY NOT NULL,
   CLASSIFICATION_ID INTEGER,
   NAME VARCHAR2(50),
   DISPLAY_LEVEL_ID INTEGER,
   DISPLAY_START_DATE TIMESTAMP,
   COMMENTS VARCHAR2(200),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.CLASSIFICATION_SERIAL;
CREATE TABLE AATAMS_2.CLASSIFICATION
(
   CLASSIFICATION_ID INTEGER PRIMARY KEY NOT NULL,
   PARENT_ID INTEGER,
   CLASSIFICATION_LEVEL VARCHAR2(50),
   NAME VARCHAR2(50),
   COMMON_NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEPLOYMENT_DOWNLOAD_SERIAL;
CREATE TABLE AATAMS_2.DEPLOYMENT_DOWNLOAD
(
   DOWNLOAD_ID INTEGER PRIMARY KEY NOT NULL,
   DEPLOYMENT_ID INTEGER,
   RECOVERY_TIMESTAMP TIMESTAMP,
   DOWNLOAD_TIMESTAMP TIMESTAMP,
   TIME_CORRECTION_START TIMESTAMP,
   TIME_CORRECTION_END TIMESTAMP,
   TIME_CORRECTION_TYPE_ID VARCHAR2(50),
   CLOCK_DRIFT INTEGER,
   PINGS INTEGER,
   DETECTIONS INTEGER,
   FILENAME VARCHAR2(100),
   COMMENTS VARCHAR2(255),
   STATUS_ID INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEPLOYMENT_EVENT_SERIAL;
CREATE TABLE AATAMS_2.DEPLOYMENT_EVENT
(
   DEPLOYMENT_EVENT_ID INTEGER PRIMARY KEY NOT NULL,
   DEPLOYMENT_ID INTEGER,
   EVENT_TYPE_ID INTEGER,
   EVENT_TIMESTAMP VARCHAR2(50),
   COMMENTS VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEPLOYMENT_EVENT_TYPE_SERIAL;
CREATE TABLE AATAMS_2.DEPLOYMENT_EVENT_TYPE
(
   EVENT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEPLOYMENT_RECOVERY_SERIAL;
CREATE TABLE AATAMS_2.DEPLOYMENT_RECOVERY
(
   RECOVERY_ID INTEGER PRIMARY KEY NOT NULL,
   DEPLOYMENT_ID INTEGER,
   RECOVERY_TIMESTAMP TIMESTAMP,
   RECOVERY_STATUS_ID INTEGER,
   COMMENTS VARCHAR2(1000),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DETECTION_SERIAL;
CREATE TABLE AATAMS_2.DETECTION
(
   DETECTION_ID INTEGER PRIMARY KEY NOT NULL,
   DEPLOYMENT_ID INTEGER,
   TAG_ID INTEGER,
   DETECTION_TIMESTAMP TIMESTAMP,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEVICE_SERIAL;
CREATE TABLE AATAMS_2.DEVICE
(
   DEVICE_ID INTEGER PRIMARY KEY NOT NULL,
   CODE_NAME VARCHAR2(50),
   DEVICE_TYPE_ID INTEGER,
   MODEL_ID INTEGER,
   SERIAL_NUMBER VARCHAR2(50),
   STATUS_ID INTEGER,
   PROJECT_ROLE_PERSON_ID INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEVICE_DEPLOYER_SERIAL;
CREATE TABLE AATAMS_2.DEVICE_DEPLOYER
(
   DEVICE_DEPLOYER_ID INTEGER PRIMARY KEY NOT NULL,
   DEPLOYMENT_ID INTEGER,
   PERSON_ID INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEVICE_DEPLOYMENT_SERIAL;
CREATE TABLE AATAMS_2.DEVICE_DEPLOYMENT
(
   DEPLOYMENT_ID INTEGER PRIMARY KEY NOT NULL,
   DEVICE_ID INTEGER,
   INSTALLATION_ID INTEGER,
   STATION_ID INTEGER,
   PROJECT_ROLE_PERSON_ID INTEGER,
   LONGITUDE DECIMAL,
   LATITUDE DECIMAL,
   DEPLOYMENT_TIMESTAMP TIMESTAMP,
   ACOUSTIC_RELEASE_ID VARCHAR2(50),
   MOORING_TYPE_ID INTEGER,
   BOTTOM_DEPTH REAL,
   COMMENTS VARCHAR2(255),
   STATUS_ID INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEVICE_MANUFACTURER_SERIAL;
CREATE TABLE AATAMS_2.DEVICE_MANUFACTURER
(
   MANUFACTURER_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEVICE_MODEL_SERIAL;
CREATE TABLE AATAMS_2.DEVICE_MODEL
(
   MODEL_ID INTEGER PRIMARY KEY NOT NULL,
   DEVICE_TYPE_ID INTEGER,
   MANUFACTURER_ID INTEGER,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DEVICE_TYPE_SERIAL;
CREATE TABLE AATAMS_2.DEVICE_TYPE
(
   DEVICE_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.DOWNLOAD_FILE_SERIAL;
CREATE TABLE AATAMS_2.DOWNLOAD_FILE
(
   DOWNLOAD_FILE_ID INTEGER PRIMARY KEY NOT NULL,
   DOWNLOAD_ID INTEGER,
   FILE_REFERENCE VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.GEOGRAPHIC_AREA_SERIAL;
CREATE TABLE AATAMS_2.GEOGRAPHIC_AREA
(
   GEOGRAPHIC_AREA_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   BOUNDARY_POINTS VARCHAR2(255),
   DESCRIPTION VARCHAR2(255),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.IMPLANT_TYPE_SERIAL;
CREATE TABLE AATAMS_2.IMPLANT_TYPE
(
   IMPLANT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.INSTALLATION_SERIAL;
CREATE TABLE AATAMS_2.INSTALLATION
(
   INSTALLATION_ID INTEGER PRIMARY KEY NOT NULL,
   CONFIGURATION_TYPE_ID INTEGER,
   LATITUDE INTEGER,
   LONGITUDE DECIMAL,
   GEOGRAPHIC_AREA_ID INTEGER,
   NAME VARCHAR2(50),
   STATUS_ID INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.INSTALLATION_CONF_SERIAL;
CREATE TABLE AATAMS_2.INSTALLATION_CONF
(
   CONFIGURATION_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.INSTALLATION_STATION_SERIAL;
CREATE TABLE AATAMS_2.INSTALLATION_STATION
(
   STATION_ID INTEGER PRIMARY KEY NOT NULL,
   INSTALLATION_ID INTEGER,
   CURTAIN_POSITION INTEGER,
   NAME VARCHAR2(50),
   LONGITUDE DECIMAL,
   LATITUDE DECIMAL,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.MEASUREMENT_SERIAL;
CREATE TABLE AATAMS_2.MEASUREMENT
(
   MEASUREMENT_ID INTEGER PRIMARY KEY NOT NULL,
   SURGERY_ID INTEGER,
   MEASUREMENT_TYPE_ID INTEGER,
   VALUE VARCHAR2(50),
   COMMENTS VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.MEASUREMENT_TYPE_SERIAL;
CREATE TABLE AATAMS_2.MEASUREMENT_TYPE
(
   MEASUREMENT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   MEASUREMENT_UNITS_ID INTEGER,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.MEASUREMENT_UNIT_TYPE_SERIAL;
CREATE TABLE AATAMS_2.MEASUREMENT_UNIT_TYPE
(
   MEASUREMENT_UNIT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.MOORING_TYPE_SERIAL;
CREATE TABLE AATAMS_2.MOORING_TYPE
(
   MOORING_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DESCRIPTION VARCHAR2(255),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.ORGANISATION_SERIAL;
CREATE TABLE AATAMS_2.ORGANISATION
(
   ORGANISATION_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   PHYSICAL_ADDRESS_1 VARCHAR2(100),
   PHYSICAL_ADDRESS_2 VARCHAR2(100),
   PHYSICAL_ADDRESS_STATE VARCHAR2(20),
   PHYSICAL_ADDRESS_COUNTRY VARCHAR2(30),
   PHYSICAL_ADDRESS_POSTCODE VARCHAR2(14),
   POSTAL_ADDRESS_1 VARCHAR2(100),
   POSTAL_ADDRESS_2 VARCHAR2(100),
   POSTAL_ADDRESS_STATE VARCHAR2(20),
   POSTAL_ADDRESS_COUNTRY VARCHAR2(50),
   POSTAL_ADDRESS_POSTCODE VARCHAR2(14),
   PHONE_NUMBER VARCHAR2(20),
   FAX_NUMBER VARCHAR2(20),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.ORGANISATION_ANIMAL_SERIAL;
CREATE TABLE AATAMS_2.ORGANISATION_ANIMAL
(
   ORGANIZATION_ID INTEGER NOT NULL,
   ANIMAL_ID INTEGER,
   ORGANIZATION_ANIMAL_ID VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.ORGANISATION_PERSON_SERIAL;
CREATE TABLE AATAMS_2.ORGANISATION_PERSON
(
   ORGANISATION_PERSON_ID INTEGER PRIMARY KEY NOT NULL,
   PERSON_ID INTEGER,
   ORGANISATION_ID INTEGER,
   POSITION VARCHAR2(50),
   PHONE_NUMBER VARCHAR2(15),
   FAX_NUMBER VARCHAR2(15),
   MOBILE_NUMBER VARCHAR2(15),
   EMAIL_ADDRESS VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.PERSON_SERIAL;
CREATE TABLE AATAMS_2.PERSON
(
   PERSON_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   PERSONAL_MOBILE_NUMBER VARCHAR2(15),
   HOME_PHONE_NUMBER VARCHAR2(15),
   HOME_PHYSICAL_ADDRESS_1 VARCHAR2(50),
   HOME_PHYSICAL_ADDRESS_2 VARCHAR2(50),
   HOME_PHYSICAL_ADDRESS_STATE VARCHAR2(50),
   HOME_PHYSICAL_ADDRESS_COUNTRY VARCHAR2(50),
   HOME_PHYSICAL_ADDRESS_POSTCODE VARCHAR2(14),
   HOME_POSTAL_ADDRESS_1 VARCHAR2(50),
   HOME_POSTAL_ADDRESS_2 VARCHAR2(50),
   HOME_POSTAL_ADDRESS_STATE VARCHAR2(50),
   HOME_POSTAL_ADDRESS_COUNTRY VARCHAR2(50),
   HOME_POSTAL_ADDRESS_POSTCODE VARCHAR2(14),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.PROJECT_SERIAL;
CREATE TABLE AATAMS_2.PROJECT
(
   PROJECT_ID INTEGER PRIMARY KEY NOT NULL,
   ORGANISATION_ID INTEGER,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.PROJECT_ROLE_PERSON_SERIAL;
CREATE TABLE AATAMS_2.PROJECT_ROLE_PERSON
(
   PROJECT_ROLE_PERSON_ID INTEGER PRIMARY KEY NOT NULL,
   PROJECT_ID INTEGER,
   ROLE_ID INTEGER,
   PERSON_ID INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.ROLE_SERIAL;
CREATE TABLE AATAMS_2.ROLE
(
   ROLE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.STATUS_SERIAL;
CREATE TABLE AATAMS_2.STATUS
(
   STATUS_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.STOCK_SERIAL;
CREATE TABLE AATAMS_2.STOCK
(
   STOCK_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.SURGERY_SERIAL;
CREATE TABLE AATAMS_2.SURGERY
(
   SURGERY_ID INTEGER PRIMARY KEY NOT NULL,
   TREATMENT_TYPE_ID INTEGER,
   PROJECT_ROLE_PERSON_ID INTEGER,
   ANIMAL_ID INTEGER,
   STOCK_ID INTEGER,
   UTC_DATETIME TIMESTAMP,
   COMMENTS VARCHAR2(255),
   UNIT VARCHAR2(50),
   MEASURE VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.SURGERY_PERSON_SERIAL;
CREATE TABLE AATAMS_2.SURGERY_PERSON
(
   SURGERY_PERSON_ID INTEGER PRIMARY KEY NOT NULL,
   SURGERY_ID INTEGER,
   PERSON_ID INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.TAG_DEVICE_SERIAL;
CREATE TABLE AATAMS_2.TAG_DEVICE
(
   DEVICE_ID INTEGER PRIMARY KEY NOT NULL,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.TAG_FAMILY_SERIAL;
CREATE TABLE AATAMS_2.TAG_FAMILY
(
   TAG_FAMILY_ID INTEGER PRIMARY KEY NOT NULL,
   MANUFACTURER_ID INTEGER,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.TAG_MODEL_SERIAL;
CREATE TABLE AATAMS_2.TAG_MODEL
(
   MODEL_ID INTEGER,
   TAG_FAMILY_ID INTEGER,
   VUE_CODING VARCHAR2(50),
   TAG_TYPE_ID INTEGER,
   FREQUENCY VARCHAR2(50),
   SYNC VARCHAR2(50),
   BIN VARCHAR2(50),
   MIN INTEGER,
   MAX INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.TAG_RELEASE_SERIAL;
CREATE TABLE AATAMS_2.TAG_RELEASE
(
   RELEASE_ID INTEGER PRIMARY KEY NOT NULL,
   DEVICE_ID INTEGER,
   CLASSIFICATION_ID INTEGER,
   PROJECT_ROLE_PERSON_ID INTEGER,
   SURGERY_ID INTEGER,
   RELEASE_LONGITUDE DECIMAL,
   RELEASE_LATITUDE DECIMAL,
   RELEASE_GEOGRAPHIC_AREA_ID INTEGER,
   RELEASE_TIMESTAMP TIMESTAMP,
   CAPTURE_LONGITUDE DECIMAL,
   CAPTURE_LATITUDE DECIMAL,
   CAPTURE_GEOGRAPHIC_AREA_ID INTEGER,
   CAPTURE_TIMESTAMP TIMESTAMP,
   TETHER_TYPE_ID INTEGER,
   IMPLANT_TYPE_ID INTEGER,
   STATUS_ID INTEGER,
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.TAG_TYPE_SERIAL;
CREATE TABLE AATAMS_2.TAG_TYPE
(
   TAG_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   MANUFACTURER_ID INTEGER,
   NAME VARCHAR2(10),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.TETHER_TYPE_SERIAL;
CREATE TABLE AATAMS_2.TETHER_TYPE
(
   TETHER_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DESCRIPTION VARCHAR2(50),
   PICTURE_REFERENCE VARCHAR2(10),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE SEQUENCE AATAMS_2.TREATMENT_TYPE_SERIAL;
CREATE TABLE AATAMS_2.TREATMENT_TYPE
(
   TREATMENT_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR2(50),
   DISABLED CHAR(1) DEFAULT 'N' NOT NULL CHECK(DISABLED IN('Y','N')),
   CREATED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
   MODIFIED TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
);

ALTER TABLE ANIMAL
ADD CONSTRAINT ANIMAL_FK00
FOREIGN KEY(CLASSIFICATION_ID)
REFERENCES CLASSIFICATION(CLASSIFICATION_ID);

ALTER TABLE DEPLOYMENT_DOWNLOAD
ADD CONSTRAINT DEPLOYMENT_DOWNLOAD_FK00
FOREIGN KEY(DEPLOYMENT_ID)
REFERENCES DEVICE_DEPLOYMENT(DEPLOYMENT_ID);

ALTER TABLE DEPLOYMENT_EVENT
ADD CONSTRAINT DEPLOYMENT_EVENT_FK00
FOREIGN KEY(EVENT_TYPE_ID)
REFERENCES DEPLOYMENT_EVENT_TYPE(EVENT_TYPE_ID);

ALTER TABLE DEPLOYMENT_EVENT
ADD CONSTRAINT DEPLOYMENT_EVENT_FK01
FOREIGN KEY(DEPLOYMENT_ID)
REFERENCES DEVICE_DEPLOYMENT(DEPLOYMENT_ID);

ALTER TABLE DEPLOYMENT_RECOVERY
ADD CONSTRAINT DEPLOYMENT_RECOVERY_FK00
FOREIGN KEY(DEPLOYMENT_ID)
REFERENCES DEVICE_DEPLOYMENT(DEPLOYMENT_ID);

ALTER TABLE DETECTION
ADD CONSTRAINT DETECTION_FK00
FOREIGN KEY(DEPLOYMENT_ID)
REFERENCES DEVICE_DEPLOYMENT(DEPLOYMENT_ID);

ALTER TABLE DEVICE
ADD CONSTRAINT DEVICE_FK00
FOREIGN KEY(MODEL_ID)
REFERENCES DEVICE_MODEL(MODEL_ID);

ALTER TABLE DEVICE
ADD CONSTRAINT DEVICE_FK01
FOREIGN KEY(DEVICE_TYPE_ID)
REFERENCES DEVICE_TYPE(DEVICE_TYPE_ID);

ALTER TABLE DEVICE
ADD CONSTRAINT DEVICE_FK02
FOREIGN KEY(PROJECT_ROLE_PERSON_ID)
REFERENCES PROJECT_ROLE_PERSON(PROJECT_ROLE_PERSON_ID);

ALTER TABLE DEVICE_DEPLOYMENT
ADD CONSTRAINT DEVICE_DEPLOYMENT_FK00
FOREIGN KEY(DEVICE_ID)
REFERENCES DEVICE(DEVICE_ID);

ALTER TABLE DEVICE_DEPLOYMENT
ADD CONSTRAINT DEVICE_DEPLOYMENT_FK02
FOREIGN KEY(INSTALLATION_ID)
REFERENCES INSTALLATION(INSTALLATION_ID);

ALTER TABLE DEVICE_DEPLOYMENT
ADD CONSTRAINT DEVICE_DEPLOYMENT_FK01
FOREIGN KEY(STATION_ID)
REFERENCES INSTALLATION_STATION(STATION_ID);

ALTER TABLE DEVICE_DEPLOYMENT
ADD CONSTRAINT DEVICE_DEPLOYMENT_FK03
FOREIGN KEY(MOORING_TYPE_ID)
REFERENCES MOORING_TYPE(MOORING_TYPE_ID);

ALTER TABLE DEVICE_DEPLOYMENT
ADD CONSTRAINT DEVICE_DEPLOYMENT_FK04
FOREIGN KEY(PROJECT_ROLE_PERSON_ID)
REFERENCES PROJECT_ROLE_PERSON(PROJECT_ROLE_PERSON_ID);

ALTER TABLE DEVICE_MODEL
ADD CONSTRAINT DEVICE_MODEL_FK00
FOREIGN KEY(MANUFACTURER_ID)
REFERENCES DEVICE_MANUFACTURER(MANUFACTURER_ID);

ALTER TABLE DEVICE_MODEL
ADD CONSTRAINT DEVICE_MODEL_FK01
FOREIGN KEY(DEVICE_TYPE_ID)
REFERENCES DEVICE_TYPE(DEVICE_TYPE_ID);

ALTER TABLE DOWNLOAD_FILE
ADD CONSTRAINT DOWNLOAD_FILE_FK00
FOREIGN KEY(DOWNLOAD_ID)
REFERENCES DEPLOYMENT_DOWNLOAD(DOWNLOAD_ID);

ALTER TABLE INSTALLATION
ADD CONSTRAINT INSTALLATION_FK00
FOREIGN KEY(GEOGRAPHIC_AREA_ID)
REFERENCES GEOGRAPHIC_AREA(GEOGRAPHIC_AREA_ID);

ALTER TABLE INSTALLATION
ADD CONSTRAINT INSTALLATION_FK01
FOREIGN KEY(CONFIGURATION_TYPE_ID)
REFERENCES INSTALLATION_CONF(CONFIGURATION_TYPE_ID);

ALTER TABLE INSTALLATION_STATION
ADD CONSTRAINT INSTALLATION_STATION_FK00
FOREIGN KEY(INSTALLATION_ID)
REFERENCES INSTALLATION(INSTALLATION_ID);

ALTER TABLE MEASUREMENT
ADD CONSTRAINT MEASUREMENT_FK00
FOREIGN KEY(MEASUREMENT_TYPE_ID)
REFERENCES MEASUREMENT_TYPE(MEASUREMENT_TYPE_ID);

ALTER TABLE MEASUREMENT
ADD CONSTRAINT MEASUREMENT_FK01
FOREIGN KEY(SURGERY_ID)
REFERENCES SURGERY(SURGERY_ID);

ALTER TABLE MEASUREMENT_TYPE
ADD CONSTRAINT MEASUREMENT_TYPE_FK00
FOREIGN KEY(MEASUREMENT_UNITS_ID)
REFERENCES MEASUREMENT_UNIT_TYPE(MEASUREMENT_UNIT_TYPE_ID);

ALTER TABLE PROJECT
ADD CONSTRAINT PROJECT_FK00
FOREIGN KEY(ORGANISATION_ID)
REFERENCES ORGANISATION(ORGANISATION_ID);

ALTER TABLE PROJECT_ROLE_PERSON
ADD CONSTRAINT PROJECT_ROLE_PERSON_FK00
FOREIGN KEY(PERSON_ID)
REFERENCES PERSON(PERSON_ID);

ALTER TABLE PROJECT_ROLE_PERSON
ADD CONSTRAINT PROJECT_ROLE_PERSON_FK01
FOREIGN KEY(PROJECT_ID)
REFERENCES PROJECT(PROJECT_ID);

ALTER TABLE PROJECT_ROLE_PERSON
ADD CONSTRAINT PROJECT_ROLE_PERSON_FK02
FOREIGN KEY(ROLE_ID)
REFERENCES ROLE(ROLE_ID);

ALTER TABLE SURGERY
ADD CONSTRAINT SURGERY_FK00
FOREIGN KEY(ANIMAL_ID)
REFERENCES ANIMAL(ANIMAL_ID);

ALTER TABLE SURGERY
ADD CONSTRAINT SURGERY_FK01
FOREIGN KEY(TREATMENT_TYPE_ID)
REFERENCES TREATMENT_TYPE(TREATMENT_TYPE_ID);

ALTER TABLE SURGERY_PERSON
ADD CONSTRAINT SURGERY_PERSON_FK00
FOREIGN KEY(PERSON_ID)
REFERENCES PERSON(PERSON_ID);

ALTER TABLE SURGERY_PERSON
ADD CONSTRAINT SURGERY_PERSON_FK01
FOREIGN KEY(SURGERY_ID)
REFERENCES SURGERY(SURGERY_ID);

ALTER TABLE TAG_MODEL
ADD CONSTRAINT TAG_MODEL_FK00
FOREIGN KEY(MODEL_ID)
REFERENCES DEVICE_MODEL(MODEL_ID);

ALTER TABLE TAG_MODEL
ADD CONSTRAINT TAG_MODEL_FK01
FOREIGN KEY(TAG_FAMILY_ID)
REFERENCES TAG_FAMILY(TAG_FAMILY_ID);

ALTER TABLE TAG_MODEL
ADD CONSTRAINT TAG_MODEL_FK02
FOREIGN KEY(TAG_TYPE_ID)
REFERENCES TAG_TYPE(TAG_TYPE_ID);

ALTER TABLE TAG_RELEASE
ADD CONSTRAINT TAG_RELEASE_FK00
FOREIGN KEY(CLASSIFICATION_ID)
REFERENCES CLASSIFICATION(CLASSIFICATION_ID);

ALTER TABLE TAG_RELEASE
ADD CONSTRAINT TAG_RELEASE_FK01
FOREIGN KEY(DEVICE_ID)
REFERENCES DEVICE(DEVICE_ID);

ALTER TABLE TAG_RELEASE
ADD CONSTRAINT TAG_RELEASE_FK02
FOREIGN KEY(IMPLANT_TYPE_ID)
REFERENCES IMPLANT_TYPE(IMPLANT_TYPE_ID);

ALTER TABLE TAG_RELEASE
ADD CONSTRAINT TAG_RELEASE_FK03
FOREIGN KEY(IMPLANT_TYPE_ID)
REFERENCES IMPLANT_TYPE(IMPLANT_TYPE_ID);

ALTER TABLE TAG_RELEASE
ADD CONSTRAINT TAG_RELEASE_FK04
FOREIGN KEY(PROJECT_ROLE_PERSON_ID)
REFERENCES PROJECT_ROLE_PERSON(PROJECT_ROLE_PERSON_ID);


ALTER TABLE TAG_RELEASE
ADD CONSTRAINT TAG_RELEASE_FK06
FOREIGN KEY(SURGERY_ID)
REFERENCES SURGERY(SURGERY_ID);

ALTER TABLE TAG_RELEASE
ADD CONSTRAINT TAG_RELEASE_FK07
FOREIGN KEY(TETHER_TYPE_ID)
REFERENCES TETHER_TYPE(TETHER_TYPE_ID);
