var species_list = [
[1,"Caranx fulvoguttatus (Yellow spotted kingfish)"],
[2,"Carcharhinus amblyrhynchos (Grey reef shark)"],
[3,"Carcharhinus cautus (Nervous shark)"],
[4,"Carcharhinus melanopterus (Blacktip reef shark)"],
[36,"Chlorurus sordidus (Bullethead parrotfish)"],
[5,"Coris aygula (Clown coris)"],
[42,"Epinephelus multinotatus (White-blotched grouper)"],
[6,"Epinephelus rivulatus (Halfmoon grouper)"],
[37,"Epinephelus tauvina (Greasy grouper)"],
[7,"Galocerdo cuvier (Tiger shark)"],
[38,"Hiposcarus longiceps (Pacific longnose parrotfish)"],
[8,"Lethrinus nebulosus (Spangled emperor)"],
[9,"Manta birostris (Manta ray)"],
[10,"Negaprion acutidens (Sicklefin lemon shark)"],
[35,"Orectolobus halei (Hale's wobbegong)"],
[39,"Orectolobus maculatus (Spotted wobbegong)"],
[11,"Pastinachus sephen (Cowtail stingray)"],
[40,"Plectropomus leopardus (Leopard coralgrouper)"],
[41,"Plectropomus maculatus (Spotted coralgrouper)"],
[12,"Rhinobatos typus (Giant shovelnose ray)"],
[32,"Scarus gobban (Blue-barred parrotfish)"],
[34,"Scarus rivulatus (Rivulated parrotfish)"],
[13,"Thunnus maccoyii (Southern bluefin tuna)"],
[14,"Urogymnus asperrimus (Porcupine ray)"],
[33,"Variola louti (Yellow-edged lyretail)"]
];
