/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecSecurityFilters 
{
    // Any controllers not specified here are only accessible to 
    // sys admin.
    def accessibleControllers = 
        ["organisation",
         "project",
         "person",
         "installation",
         "installationStation",
         "receiver",
         "tag",
         "animalRelease",
         "detection",
         "receiverDeployment",
         "receiverRecovery"]
    
    //
    // Anyone can execute the following actions (even if not
    // authenticated).
    //
    // Note that some entities may be filtered after action executes if not 
    // authenticated, e.g. embargoed data, scrambled station locations.
    //
    def publicActions =
        ["index",
         "list",
         "show"]
                
    def filters = 
    {
        all(uri: "/**") 
        {
            before = 
            {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

                // Anyone should be able to see the navigation menu.
                if (controllerName == "navigationMenu")
                {
                    return true
                }
                
                if (!accessibleControllers.contains(controllerName))
                {
                    accessControl
                    {
                        role("SysAdmin")
                    }
                }
                else
                {
                    if (publicActions.contains(actionName))
                    {
                        return true
                    }

                    // Access control by convention.
                    accessControl()
                }
            }
        }
    }
}
